language: bash
# Travis build lifecycle https://docs.travis-ci.com/user/customizing-the-build#The-Build-Lifecycle

sudo: true
services:
  - docker
env:
  - KCOV_IMG="ragnaroek/kcov:v33"
cache:
  bundler: true
  directories: $HOME/docker

matrix:
  include:
    - os: linux
    - os: osx

before_install:
 - if [[ -f "$HOME/docker/kcov" ]]; then docker load -i "$HOME/docker/kcov"; fi

before_script:
  - chmod +x test/unittest.sh
  - chmod +x bin/timelog
  - chmod +x test/test_dep.sh
  - export PATH=$PATH:$PWD/bin/
  - pushd test/
  - ./test_dep.sh
  - popd

script:
  - export PATH=$PATH:$PWD/bin/
  - pushd test/
  - ./unittest.sh
  - popd
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./runMetrics.sh $KCOV_IMMG; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cd metrics; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then bash <(curl -s https://codecov.io/bash); fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./test/mac_kcov.sh; fi

before_cache:
  - docker save $KCOV_IMG -o "$HOME/docker/kcov"
