language: bash

sudo: false

before_script:
  - chmod +x test/unittest.sh
  - chmod +x bin/timelog
  - chmod +x test/test_dep.sh
  - export PATH=$PATH:$PWD/bin/
  - pushd test/
  - ./test_dep.sh
  - popd

script:
  - export PATH=$PATH:$PWD/bin/
  - pushd test/
  - bash unittest.sh
  - popd
