#!/bin/bash
week=27
file=$(cat ~/.config/timelogs/Test.logs)
set_of_years=$(echo "$file" | grep "^[0-9]*-$week-[1-7]*" | grep -o '^[0-9]*' | uniq | sort -n)
how_many=$(echo "$set_of_years" | wc -l)
year=$(echo "$set_of_years" | sort -nr | head -n1)

if [ $how_many -gt 1 ]; then
  # User has more than one year in his/her log. This means that the same week can be found for one or multiple years
  # Notify the user that the year can be re-picked
  echo "$(tput setaf 5)Note:$(tput setaf 7) You have multiple logs that has different years for the week $week"
  echo "You can re-run the program to specify what year, but the program will default to the latest year $year."
fi
